# Generated by Django 4.0.1 on 2022-01-22 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('meal_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('meal_name', models.CharField(max_length=100)),
                ('meal_image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('meal_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=100)),
                ('location_image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('categories', models.ManyToManyField(to='main.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=100)),
                ('hotel_icon_image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('hotel_image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('hotel_price_for_night', models.IntegerField()),
                ('hotel_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.location')),
            ],
        ),
    ]
