# Generated by Django 4.0.1 on 2022-01-23 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_location',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.location'),
            preserve_default=False,
        ),
    ]
