# Generated by Django 4.0.1 on 2022-01-23 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_hotel_hotel_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.location'),
        ),
    ]
