# Generated by Django 4.0.1 on 2022-01-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_meal_meal_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_icon',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
