# Generated by Django 4.0.1 on 2022-01-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_adress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
